server :
  port : 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_water?serverTimezone=UTC&characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: root
    password: 621020
    driver-class-name: com.mysql.cj.jdbc.Driver

    #    filters: wall,stat
    #    max-active: 12
    druid:
      aop-patterns: com.example.admin.*  #监控SpringBean
      filters: stat,wall,slf4j     # 底层开启功能，stat（sql监控），wall（防火墙）

      stat-view-servlet:   # 配置监控页功能
        enabled: true
        login-username: admin
        login-password: admin
        resetEnable: false

      web-stat-filter:  # 监控web
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'


      filter:
        stat:    # 对上面filters里面的stat的详细配置
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false
  jdbc:
    template:
      query-timeout: 3

  redis:
    database: 0
    host: localhost         # Redis服务器地址
    port: 6379              # Redis服务器连接端口
    password:               # Redis服务器连接密码（默认为空）
    pool:
      max-active: 200       # 连接池最大连接数（使用负值表示没有限制）
      max-idle: 10          # 连接池中的最大空闲连接
      max-wait: -1          # 连接池最大阻塞等待时间（使用负值表示没有限制）
      min-idle: 0           # 连接池中的最小空闲连接
    timeout: 1000
    client-type: jedis      #客户端类型为jedis
  #      3秒超时
#配置mybaties规则
mybatis:
  #  config-location: classpath:mybatis/mybatis-config.xml  #全局配置文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml  #sql映射文件位置
  configuration: #  指定mybatis全局配置文件中的相关配置
    map-underscore-to-camel-case: true

#阿里云配置
aliyun:
  oss:
      endpoint: oss-cn-chengdu.aliyuncs.com
      accessKeyId: LTAI5tQC957TEzVAzB6XRxVB
      accessKeySecret: JYCLpf7dGitpsEwRfDMAjlEQ3UhgDJ
      bucketname: water-level-picture
      urlPrefix: